/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import comunicacion.ConcreateCreatorComunicacion;
import comunicacion.IComunicacion;
import java.util.ArrayList;
import negocio.IJugador;

/**
 *
 * @author Fernando
 */
public class FrmSalaEspera extends javax.swing.JFrame {

    public static FrmSalaEspera instance;
    
    IJugador jugador;
    
    ArrayList<IJugador> jugadores = new ArrayList();
    
    ConcreateCreatorComunicacion fabrica = new ConcreateCreatorComunicacion();
    
    IComunicacion comunicacion = (IComunicacion) fabrica.FactoryMethod("Proxy");
    
    /**
     * Creates new form frmSalaEspera
     */
    private FrmSalaEspera(IJugador jugador) {
        initComponents();
        this.jugador = jugador;
        lblAvatar1.setIcon(jugador.getAvatar());
//        IFacadePartida partida = 
        setVisible(true);
    }

    public static FrmSalaEspera obtenerInstancia(IJugador jugador){
        
        if(instance == null){
            instance = new FrmSalaEspera(jugador);
        }
        
        return instance;
    }

    public ArrayList<IJugador> getJugadores() {
        return jugadores;
    }

    public void setJugadorListo(IJugador jugador){
        System.out.println("si llego a setarlo al frame");
        int aux = 0;
        for (int i = 0; i < jugadores.size(); i++) {
            if(jugadores.get(i).getPuerto() == jugador.getPuerto()){
                aux = i;
                break;
            }
        }
        System.out.println(aux);
        if(aux == 0){
            lblEstado1.setText("Listo");
        }
        if(aux == 1){
            lblEstado2.setText("Listo");
        }
        if(aux == 2){
            lblEstado3.setText("Listo");
        }
    }
    
    
    public void iniciarLaPartida(){
        setVisible(false);
        FrmPartida frm = FrmPartida.obtenerInstancia();
        frm.setVisible(true);
    }
    
    public void setJugadores(ArrayList<IJugador> jugadores) {
        this.jugadores = jugadores;
        for (int i = 0; i < jugadores.size(); i++) {
            if(jugadores.get(i).isEstado()){
                if(i == 0){
                lblEstado1.setText("Listo");
                }
                if(i == 1){
                    lblEstado2.setText("Listo");
                }
                if(i == 2){
                    lblEstado3.setText("Listo");
                }
            }
        }
        
        
        if(jugadores.size() == 1){
            lblAvatar1.setIcon(jugadores.get(0).getAvatar());
        }
        if(jugadores.size() == 2){
            lblAvatar1.setIcon(jugadores.get(0).getAvatar());
            lblAvatar2.setIcon(jugadores.get(1).getAvatar());
        }
        if(jugadores.size() == 3){
            lblAvatar1.setIcon(jugadores.get(0).getAvatar());
            lblAvatar2.setIcon(jugadores.get(1).getAvatar());
            lblAvatar3.setIcon(jugadores.get(2).getAvatar());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblAvatar2 = new javax.swing.JLabel();
        lblAvatar1 = new javax.swing.JLabel();
        lblAvatar3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setText("Numero de jugadores");

        lblAvatar2.setText("FOTO");

        lblAvatar1.setText("FOTO");

        lblAvatar3.setText("FOTO");

        btnIniciar.setText("Iniciar Partida");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        lblEstado1.setText("No listo");

        lblEstado2.setText("No listo");

        lblEstado3.setText("No listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIniciar)
                            .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado3)
                            .addComponent(lblEstado2)
                            .addComponent(lblEstado1)
                            .addComponent(btnCancelar))))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(btnCancelar))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        System.out.println("Clickqueamos el puto boton");
        comunicacion.iniciarPartida(jugador);
    }//GEN-LAST:event_btnIniciarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmSalaEspera().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    // End of variables declaration//GEN-END:variables

    
}
